# Japari Park
#
# * Frontend
#   -- FriendsWeb
#   -- AccountsWeb
#
# * Backend
#   -- JapariService
#      -- Friends app
#      -- Accounts app
#
name: japaripark


networks:
  japari_frontend:
    driver: bridge
  friends_web_bridge:
    driver: bridge

secrets:
  japari_service_django_secret:
    file: ./Backend/JapariService/secrets/.django.secret
  japari_service_user_pass:
    file: ./Backend/JapariService/secrets/.docker-build.secret
  friends_web_user_pass:
    file: ./Frontend/FriendsWeb/secrets/.docker-build.secret


services:
  # JapariService: the main backend service
  japari_service:
    container_name: JapariService
    stdin_open: true
    tty: true
    build:
      context: ./Backend/JapariService/
      secrets:
        - japari_service_user_pass
    image: japari_service:latest
    volumes:
      - type: bind
        source: ./Backend/JapariService/logs
        target: /JapariService/logs
    secrets:
      - source: japari_service_django_secret
        target: /JapariService/secrets/.django.secret
        uid: '1000'
        gid: '1000'
        mode: 0440
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    networks:
      japari_frontend:
        priority: 0
        aliases:
          - japari-service
    environment:
      - NETWORK=japari_frontend
      - NETWORK_ALIAS=japari-service
    restart: on-failure
    stop_grace_period: 10s

  # FriendsWeb: Gunicorn server
  friends_web:
    container_name: FriendsWeb
    stdin_open: true
    tty: true
    build:
      context: ./Frontend/FriendsWeb/
      secrets:
        - friends_web_user_pass
    image: friends_web:latest
    volumes:
      - type: bind
        source: ./Frontend/FriendsWeb/logs
        target: /FriendsWeb/logs
    networks:
      friends_web_bridge:
        aliases:
          - friends-web
    environment:
      - NETWORK=friends_web_bridge
      - NETWORK_ALIAS=friends-web
    restart: on-failure
    stop_grace_period: 10s

  # FriendsWeb: NGINX reverse-proxy
  friends_web_nginx:
    container_name: FriendsWebNginx
    stdin_open: true
    tty: true
    depends_on:
      friends_web:
        condition: service_started
      japari_service:
        condition: service_started
    build:
      context: ./Frontend/FriendsWeb/
      dockerfile: ./NGINX/Dockerfile
      secrets:
        - friends_web_user_pass
    image: friends_web_proxy:latest
    volumes:
      - type: bind
        source: ./Frontend/FriendsWeb/logs/servers
        target: /FriendsWebNginx/logs
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      friends_web_bridge:
        priority: 1
        aliases:
          - friends-web-proxy
      japari_frontend:
        priority: 0
        aliases:
          - friends-web
    environment:
      - NETWORK=friends_web_bridge
      - NETWORK_ALIAS=friends-web-proxy
    restart: on-failure
    stop_grace_period: 10s
