# Japari Park
#
# * Frontend
#   -- FriendsWeb
#   -- AccountsWeb
#
# * Backend
#   -- JapariService
#      -- Friends app
#      -- Accounts app
#
# * Database
#   -- JapariDB
#
# `docker compose up --detach --build`
name: japaripark


networks:
  data_overlay:
    # aliases: japari-db.api
    driver: overlay
    attachable: true

  frontend_overlay:
    # aliases: japari-service.rest, friends-web.rest
    driver: overlay
    attachable: true

  friends_web_bridge:
    driver: bridge


secrets:
  japari_data_user_pass:
    file: ./Database/JapariDB/secrets/.docker-build.secret
  japari_data_postgres_pass:
    file: ./Database/JapariDB/secrets/.postgres_pass.secret

  japari_service_django_secret:
    file: ./Backend/JapariService/secrets/.django.secret
  japari_service_user_pass:
    file: ./Backend/JapariService/secrets/.docker-build.secret

  friends_web_user_pass:
    file: ./Frontend/FriendsWeb/secrets/.docker-build.secret


configs:
  japari_data_postgres_config:
    file: ./Database/JapariDB/configs/configs


services:
  # JapariDB: a mono database
  japari_db:
    container_name: JapariDB
    stdin_open: true
    tty: true
    build:
      context: ./Database/JapariDB/
      secrets:
        - japari_data_user_pass
    image: japari_db
    volumes:
      - type: bind
        source: ./Database/JapariDB/logs
        target: /JapariDB/logs
    configs:
      - source: japari_data_postgres_config
        target: /JapariData/configs/dummy
        uid: '1000'
        gid: '70'
        mode: 0444
    secrets:
      - source: japari_data_postgres_pass
        target: /run/secrets/postgres_pass
        uid: '1000'
        gid: '70'
        mode: 0440
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pass
    # ports:
    #   - target: 5432
    #     published: 5432
    #     protocol: tcp
    #     mode: host
    networks:
      data_overlay:
        aliases:
          - japari-db.api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luckybot -d japari_park_database \
                           -h japari-db.api -p 5432 -t 5 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 15s
    restart: on-failure
    stop_grace_period: 10s

  # JapariService: the main backend service
  japari_service:
    container_name: JapariService
    stdin_open: true
    tty: true
    # depends_on:
    #   japari_db:
    #     condition: service_started
    build:
      context: ./Backend/JapariService/
      secrets:
        - japari_service_user_pass
    image: japari_service
    volumes:
      - type: bind
        source: ./Backend/JapariService/logs
        target: /JapariService/logs
    secrets:
      - source: japari_service_django_secret
        target: /JapariService/secrets/.django.secret
        uid: '1000'
        gid: '1000'
        mode: 0440
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host
    networks:
      frontend_overlay:
        priority: 0
        aliases:
          - japari-service.rest
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://japari-service.rest/ping || exit 1"]
      interval: 3m
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: on-failure
    stop_grace_period: 10s

  # FriendsWeb: Gunicorn server
  friends_web_app:
    container_name: FriendsWeb
    stdin_open: true
    tty: true
    build:
      context: ./Frontend/FriendsWeb/
      secrets:
        - friends_web_user_pass
    image: friends_web
    volumes:
      - type: bind
        source: ./Frontend/FriendsWeb/logs
        target: /FriendsWeb/logs
    networks:
      friends_web_bridge:
        aliases:
          - friends-web.app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://frinds-web.app/ping || exit 1"]
      interval: 3m
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: on-failure
    stop_grace_period: 10s

  # FriendsWeb: NGINX reverse-proxy
  friends_web_nginx:
    container_name: FriendsWebNginx
    stdin_open: true
    tty: true
    # depends_on:
    #   friends_web_app:
    #     condition: service_started
    #   japari_service:
    #     condition: service_started
    #   japari_db:
    #     condition: service_started
    build:
      context: ./Frontend/FriendsWeb/
      dockerfile: ./NGINX/Dockerfile
      secrets:
        - friends_web_user_pass
    image: friends_web_proxy
    volumes:
      - type: bind
        source: ./Frontend/FriendsWeb/logs/servers
        target: /FriendsWebNginx/logs
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks:
      friends_web_bridge:
        priority: 1
        aliases:
          - friends-web.proxy
      frontend_overlay:
        priority: 0
        aliases:
          - friends-web.rest
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://friends-web.rest/proxy/ping/ || exit 1"]
      interval: 3m
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: on-failure
    stop_grace_period: 10s
