name: japaripark

networks:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
  admin_net:
    driver: bridge

configs:
  friends_web_conf:
    file: "./Frontend/FriendsWeb/configs/config_frontend.cfg"

secrets:
  friends_web_secret:
    file: "./Frontend/FriendsWeb/secrets/.frontend_secrets.json"

services:
  friends_web:
    container_name: FriendsWeb
    stdin_open: true
    tty: true

    build:
      context: ./Frontend/FriendsWeb
      dockerfile: Dockerfile
    deploy:
      endpoint_mode: vip
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2

    volumes:
      - type: bind
        source: "./Frontend/FriendsWeb/tests"
        target: "/FriendsWeb/tests"
        read_only: true
      - type: bind
        source: "./Frontend/FriendsWeb/helpers"
        target: "/FriendsWeb/helpers"
        read_only: true
      - type: bind
        source: "./Frontend/FriendsWeb/friends"
        target: "/FriendsWeb/friends"
        read_only: true

    ports:
#       - "5000:5000"
      - target: 5000
        host_ip: japaripark.net
        published: "5000"

    configs:
      - source: friends_web_conf
        target: /configs/friends
    secrets:
      - source: friends_web_secret
        target: /secrets/friends

    networks:
      admin_net:
        priority: 2
        aliases:
          - friends-web
      back_net:
        priority: 1
        aliases:
          - friends-web
      front_net:
        priority: 0
        aliases:
          - friends-web
          - japari-friends
    #external_links:
    #  - backend
    #extra_hosts:
    #  backend: "1.1.1.1"

    healthcheck:
      test: curl -fs "http://japaripark.net:5000/friends/ping" || echo 1
      interval: 180s
      timeout: 10s
      retries: 2
      start_period: 20s
