# Japari Park - pgAdmin
#
# `docker compose up --detach --build`
#
name: japaripark-pgadmin


networks:
  data_overlay:
    driver: overlay
    attachable: true


secrets:
  pgadmin_build_pass:
    file: ./secrets/.docker-build.secret

  pgadmin_pass:
    file: ./secrets/.pgadmin_pass.secret


services:
  japari_pgadmin:
    container_name: pgAdmin
    stdin_open: true
    tty: true
    build:
      context: .
      secrets:
        - pgadmin_build_pass
    image: japari_pgadmin
    volumes:
      - type: bind
        source: ./mnt-data/pgadata
        target: /var/lib/pgadmin
      - type: bind
        source: ./mnt-logs
        target: /JapariPGA/logs
    secrets:
      - source: pgadmin_pass
        target: /run/secrets/pgadmin_pass
        uid: '5050'
        gid: '5050'
        mode: 400
    environment:
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_pass
    ports:
      - target: 80
        published: 5050
        protocol: tcp
        mode: host
    networks:
      data_overlay:
        aliases:
          - pgadmin.api
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://pgadmin.api/login -o /dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 20s
    restart: on-failure
    stop_grace_period: 10s
