#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
echo "[ Git pre-commit ]"

## Filter non-ASCII file names
allownonascii=$(git config --type=bool hooks.allownonascii)
if [ "$allownonascii" != "true" ] &&
  test $(git diff --cached --name-only --diff-filter=A -z $against |
    LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
  cat <<\EOF
Error: Attempt to add a non-ASCII file name.
If you know what you are doing you can disable this check using:
  git config hooks.allownonascii true
EOF
  exit 1
fi

## Filter flake8
errors=0
for ell in $(git diff --cached --name-only --diff-filter=ACM)
do
  if [ -d $ell ]
  then
    continue
  elif echo "$ell" | grep -q ".py"
  then
    output=$(flake8 $ell)
    if [ -z "$output" ]
    then
      echo "flake8 [OK] -- $ell"
    else
      echo "flake8 [ERRORS] -- $ell"
      echo "$output"
      errors=$((1 + errors))
    fi
  else
    echo "flake8 [SKIPPED] -- $ell"
  fi
done

if [ $errors -ne 0 ]
then
  echo "flake8 errors count: $errors"
  echo "Commit aborted."
  exit 1
fi

exit 0
