# Generated by Django 4.2.2 on 2023-06-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listentry',
            options={'verbose_name': 'List entry', 'verbose_name_plural': 'List entries'},
        ),
    ]
