# Generated by Django 4.2.2 on 2023-07-03 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_listentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEntry',
            fields=[
                ('id', models.SmallAutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(error_messages={'blank': 'the test neads a text'}, max_length=32, unique_for_date='pub_date', verbose_name='text')),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime, editable=False, verbose_name='date published')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_core_entry_set', to=settings.AUTH_USER_MODEL, verbose_name='test core-app entries')),
            ],
            options={
                'verbose_name': 'test core-app entry',
                'verbose_name_plural': 'test core-app entries',
                'db_table': 'test_core',
                'ordering': ['pub_date'],
                'get_latest_by': ['pub_date'],
            },
        ),
        migrations.DeleteModel(
            name='ListEntry',
        ),
    ]
