# Generated by Django 4.2.2 on 2023-07-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testentry_delete_listentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testentry',
            name='owner',
        ),
    ]
