# Mono database of Japari Park
# PostgreSQL
# `docker compose up --detach --build`
#
name: japaripark-database


networks:
  data_overlay:
    driver: overlay
    attachable: true


secrets:
  japari_data_user_pass:
    file: ./secrets/.docker-build.secret

  japari_data_postgres_pass:
    file: ./secrets/.postgres_pass.secret


configs:
  japari_data_postgres_config:
    file: ./configs/configs


services:
  japari_db:
    container_name: JapariDB
    stdin_open: true
    tty: true
    build:
      context: .
      secrets:
        - japari_data_user_pass
    image: japari_db
    volumes:
      - type: bind
        source: ./mnt-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./mnt-logs
        target: /JapariDB/logs
    configs:
      - source: japari_data_postgres_config
        target: /JapariData/configs/dummy
        uid: '1000'
        gid: '70'
        mode: 440
    secrets:
      - source: japari_data_postgres_pass
        target: /run/secrets/postgres_pass
        uid: '1000'
        gid: '70'
        mode: 400
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pass
    # ports:
    #   - target: 5432
    #     published: 5432
    #     protocol: tcp
    #     mode: host
    networks:
      data_overlay:
        aliases:
          - japari-db.api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luckybot -d japari_park_database \
                           -h japari-db.api -p 5432 -t 5 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 20s
    restart: on-failure
    stop_grace_period: 10s
