FROM python:3.11-alpine3.18 as builder
WORKDIR /FriendsWeb

RUN python -m venv /FriendsWeb/venv
ENV PATH="/FriendsWeb/venv/bin:$PATH"

COPY ./requirements.txt .
RUN pip install -r requirements.txt
# </builder>


FROM python:3.11-alpine3.18
WORKDIR /FriendsWeb

# Set up a new user
ENV GID=1001
ENV UID=1000
ENV USER=luckybot

RUN addgroup $GID \
    && adduser \
        --disabled-password \
        --no-create-home \
        --gecos "" \
        --ingroup $GID \
        --uid $UID \
        $USER

# Add to the administrators group;
# add to the network connections management;
RUN addgroup $USER wheel && addgroup $USER netdev


# Copy the project files
COPY ./manage.py .

# Make a docker-flag-file;
# and resolve files permissions:
RUN touch indocker \
    && chown -R $USER:$GID /FriendsWeb


# Make dirs for the future volumes
RUN mkdir tests friends helpers

# Get the venv from builder
COPY --from=builder /FriendsWeb/venv /FriendsWeb/venv
ENV PATH="/FriendsWeb/venv/bin:$PATH"


# Login as the user
USER luckybot
# don't forget the venv path
ENV PATH="/FriendsWeb/venv/bin:$PATH"


# Entry with base tests
ENTRYPOINT ["/bin/sh", "-c", "python manage.py test ./tests/base && python -OO manage.py"]
