# Frontend web-application of Japari Park: Friends
# `docker compose up --detach --build`
name: japaripark-friend_web


networks:
  frontend_overlay:
    driver: overlay
    attachable: true


secrets:
  friends_web_build_pass:
    file: ./secrets/.docker-build.secret


configs:
  friends_web_server_conf:
    file: ./configs/gunicorn.conf.py


services:
  friends_web_app:
    container_name: FriendsWeb
    stdin_open: true
    tty: true
    build:
      context: .
      secrets:
        - friends_web_build_pass
    image: friends_web
    volumes:
      - type: bind
        source: ./mnt-logs
        target: /FriendsWeb/mnt-logs
    configs:
      - source: friends_web_server_conf
        target: /FriendsWeb/configs/gunicorn.conf.py
        uid: '1000'
        gid: '1000'
        mode: 0550
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks:
      frontend_overlay:
        aliases:
          - friends-web.rest
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://friends-web.rest/ping -o /dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 800M
    restart: on-failure
    stop_grace_period: 10s
