# Backend of Japari Park
# Daphne serving a Django application
# `docker compose up --detach --build`
#
name: japaripark-backend


networks:
  japari_frontend:
    driver: bridge

secrets:
  japari_service_user_pass:
    file: ./secrets/.docker-build.secret
  japari_service_django_secret:
    file: ./secrets/.django.secret


services:
  japari_service:
    container_name: JapariService
    stdin_open: true
    tty: true
    build:
      context: .
      secrets:
        - japari_service_user_pass
    image: japari_service:latest
    volumes:
      - type: bind
        source: ./logs
        target: /JapariService/logs
    secrets:
      - source: japari_service_django_secret
        target: /JapariService/secrets/.django.secret
        uid: '1000'
        gid: '1000'
        mode: 0440
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    networks:
      japari_frontend:
        priority: 0
        aliases:
          - japari-service
    environment:
      - NETWORK=japari_frontend
      - NETWORK_ALIAS=japari-service
    restart: on-failure
    stop_grace_period: 10s
