# Backend of Japari Park
# Daphne serving a Django application.
# `docker compose up --detach --build`
#
name: japaripark-backend


networks:
  frontend_overlay:
    driver: overlay
    attachable: true

  data_overlay:
    driver: overlay
    attachable: true


secrets:
  japari_service_build_pass:
    file: ./secrets/.docker-build.secret

  japari_service_django_secret:
    file: ./secrets/.django.secret

  japari_service_postgres_pass:
    file: ./secrets/.postgres_pass.secret


services:
  japari_service:
    container_name: JapariService
    stdin_open: true
    tty: true
    build:
      context: .
      secrets:
        - japari_service_build_pass
    image: japari_service
    volumes:
      - type: bind
        source: ./mnt-logs
        target: /JapariService/logs
      - type: bind
        source: ./mnt-data
        target: /JapariService/mnt-data
    secrets:
      - source: japari_service_django_secret
        target: /run/secrets/django_secret
        uid: '1000'
        gid: '1000'
        mode: 400
      - source: japari_service_postgres_pass
        target: /run/secrets/postgres_pass
        uid: '1000'
        gid: '1000'
        mode: 400
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host
    networks:
      data_overlay:
        priority: 1
        aliases:
          - japari-service.rest
      frontend_overlay:
        priority: 0
        aliases:
          - japari-service.rest
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://japari-service.rest/ping -o /dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: on-failure
    stop_grace_period: 10s
